Repository OpenSourceRaidGuild/website, pull requests merged in 2021-01, with the labels that each got.

#3 Developer Tooling and Potential Routes
  frontend/.eslintrc.json
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/components/UserStatBlock.svelte
  frontend/src/routes/characters/index.svelte
  frontend/src/routes/dungeons/parties/index.svelte
  frontend/src/routes/dungeons/raids/ViewRaid.svelte
  frontend/src/routes/dungeons/raids/index.svelte
  frontend/src/routes/raids/ViewRaid.svelte
  frontend/svelte.config.js
  frontend/yarn.lock
Labels: Type: Enhancement

#5 fix: add prettier-plugin-svelte and prettierrc to fix rules
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/package.json
Labels: Type: Bug

#6 feat: list all raids on /raids
  frontend/.eslintrc.json
  frontend/.vscode/settings.json
  frontend/jest.config.js
  frontend/package.json
  frontend/public/index.css
  frontend/public/index.html
  frontend/snowpack.config.js
  frontend/src/App.svelte
  frontend/src/__tests__/App.test.ts
  frontend/src/components/Card.svelte
  frontend/src/components/LoadingSpinner.svelte
  frontend/src/components/UserStatBlock.svelte
  frontend/src/index.ts
  frontend/src/routes/NotFound.svelte
  frontend/src/routes/dungeons/raids/ViewRaid.svelte
  frontend/src/routes/dungeons/raids/index.svelte
  frontend/src/routes/quests/index.svelte
  frontend/src/setupTests.ts
  frontend/svelte.config.js
  frontend/tsconfig.json
  frontend/types/static.d.ts
  frontend/types/viewRaid.d.ts
  frontend/yarn.lock
Labels: Priority: High, Priority: Medium, Status: Completed, Type: Feature

#9 fix: use spaces instead of tabs
  README.md
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/.vscode/settings.json
  frontend/jest.config.js
  frontend/package.json
  frontend/public/index.css
  frontend/public/index.html
  frontend/snowpack.config.js
  frontend/src/App.svelte
  frontend/src/__tests__/App.test.ts
  frontend/src/components/Card.svelte
  frontend/src/components/LoadingSpinner.svelte
  frontend/src/components/UserStatBlock.svelte
  frontend/src/index.ts
  frontend/src/routes/dungeons/raids/ViewRaid.svelte
  frontend/src/routes/dungeons/raids/index.svelte
  frontend/svelte.config.js
  frontend/tsconfig.json
  frontend/types/static.d.ts
  frontend/types/viewRaid.d.ts
Labels: Items: Uncommon, Side Quest: Solo, Type: Toolchain

#14 Remove code style rules from eslint
  frontend/.eslintrc.json
Labels: Status: Completed, Type: Toolchain

#2 Link user card to github page
  frontend/src/components/UserStatBlock.svelte
Labels: Status: Completed, Type: Enhancement

#31 Setup ESLint
  .eslintrc.json
  jest.config.js
  package.json
  src/routes/Home.tsx
  src/routes/NotFound.tsx
  src/routes/raids/ViewRaid.tsx
  src/routes/raids/index.tsx
  types/static.d.ts
  yarn.lock
Labels: Priority: High, Type: Toolchain

#35 Yago/loading spinner
  src/App.tsx
  src/components/card/index.tsx
  src/components/loading-spinner/index.tsx
  src/route.config.ts
Labels: Status: Pending, Type: Enhancement

#45 Simple CI
  .gitattributes
  .github/workflows/validate.yml
  package.json
  snowpack.config.js
Labels: Priority: High, Type: Toolchain

#53 chore: Precommit setup
  lint-staged.config.js
  package.json
  yarn.lock
Labels: Status: Pending, Type: Toolchain

#56 Run precommit only on changed files
  lint-staged.config.js
Labels: Type: Toolchain

#57 feat: add basic css variable design system, move reset to separate file
  src/styles/globalStyles.ts
  src/styles/reset.ts
Labels: Priority: Critical 🚨, Type: Toolchain 🧰

#58 feat: add sorting back to ViewRaid page
  src/routes/raids/ViewRaid.tsx
Labels: Status: Pending ⏳, Type: Feature

#62 Refactoring styles
  src/components/card/index.tsx
  src/components/loading-spinner/index.tsx
  src/components/user-stat-block/index.tsx
  src/routes/raids/ViewRaid.tsx
  src/styles/globalStyles.ts
  src/styles/reset.ts
Labels: Type: Enhancement, Type: Refactor 🍂

#61 refactor: add rule to turn off no-onchange and changed onBl…
  .eslintrc.json
  src/routes/raids/ViewRaid.tsx
Labels: Type: Toolchain 🧰

#66 feat: 🎨 add mobile styles to ViewRaid and UserStatBlock
  src/components/user-stat-block/index.tsx
  src/routes/raids/ViewRaid.tsx
  src/styles/globalStyles.ts
Labels: Priority: High ⚠️, Type: Enhancement

#71 feat(Routing): change to declerative routing
  src/App.tsx
  src/route.config.ts
  src/routes/AllRaids.tsx
  src/routes/ViewRaid.tsx
Labels: Items: Uncommon, Priority: Medium, Raid: Trash Mobs, Type: Refactor 🍂

#72 Suggestion for Feedback form
  src/App.tsx
  src/components/feedback/Feedback.stories.tsx
  src/components/feedback/index.tsx
  src/components/loadingSpinner/LoadingSpinner.stories.tsx
  src/components/loadingSpinner/index.tsx
  src/components/popUp/PopUp.stories.tsx
  src/components/popUp/index.tsx
  src/components/userStatBlock/UserStatBlock.stories.tsx
  src/components/userStatBlock/index.tsx
  src/routes/AllRaids.tsx
  src/routes/Home.tsx
  src/routes/ViewRaid.tsx
Labels: Status: In Progress 🚧, Status: Merge Conflict 🛑 🏗️, Status: Revision Needed, Type: Feature
